### ISSUE TITLE
Proxy configuration with grpcurl

### ISSUE THREAD

**Issue by puneetsar** [fullstorydev/grpcurl#221] opened 2021-03-17 23:04 UTC
Our environment has a forward proxy, and we need equivalent of this curl option in grpcurl:

curl http://example.com --proxy 127.0.0.1:8080

Is it possible?

**Comment by jhump** [comment] 2021-03-31 13:14
It looks like the Go runtime for gRPC, which is what grpcurl uses under its hood, supports environment variables in a similar fashion as curl and python: `HTTP_PROXY`, `HTTPS_PROXY`, and `NO_PROXY` can inform the program how to route a request through a proxy.

So I think the following would work. Please try it out:
```
HTTP_PROXY=127.0.0.1:8080 grpcurl ...
```

**Comment by jhump** [comment] 2021-03-31 13:16
Closing this issue because it is a duplicate of #166

**Closed by jhump** 2021-03-31 13:16 UTC
